[build]
  # Static site at repo root
  publish = "."

# (Optional but safe) SPA fallback so refreshes/deep links work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy all frontend calls to your Render backend
[[redirects]]
  from = "/api/*"
  to = "https://answerlybyvaryonglobal.onrender.com/:splat"
  status = 200
  force = true
